services:
  drugref:
    container_name: drugref2026-tomcat-dev
    build:
      context: ./development
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "18000:8000"
    volumes:
      - m2-volume:/root/.m2
      - ..:/workspace:cached
    env_file:
      - ./development/config/local.env
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      TZ: America/Toronto
    networks:
      - drugref-network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: drugref2026-mariadb-dev
    image: mariadb:10.11
    env_file:
      - ./development/config/local.env
    environment:
      MYSQL_DATABASE: drugref2
      TZ: America/Toronto
    ports:
      - "3306:3306"
    volumes:
      - mariadb-files:/var/lib/mysql
    networks:
      - drugref-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 60s

volumes:
  mariadb-files:
    driver: local

  m2-volume:
    driver: local

networks:
  drugref-network:
    driver: bridge
    name: drugref2026-network
